### ISSUE TITLE
invalid syntax from file strategy_multi_bitget.py

### ISSUE THREAD

**Issue by SToXiT** [CryptoRobotFr/live_tools#7]
i got these error :

File "live_tools/strategies/bol_trend/strategy_multi_bitget.py", line 460
    now = datetime.now()
    ^
SyntaxError: invalid syntax

i've try to delete the 460 line and what is after but it move the problem to :

File "live_tools/strategies/bol_trend/strategy_multi_bitget.py", line 459
    print("""--- End Execution Time :""", current_time, """---""")
    ^
SyntaxError: invalid syntax

**Comment by CryptoRobotFr** [comment]
En effet il manquait une paranthèse fermée. C'est corrigé merci
